name: CI

on: [push, pull_request]

jobs:
  flatpak-builder:
    runs-on: ubuntu-latest

    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged

    steps:
    - uses: actions/checkout@v2
    - run: meson build
    - uses: bilelmoussaoui/flatpak-github-actions@master
      with:
        bundle: "io.elementary.Sdk.Nightly"
        manifest-path: "build/io.elementary.Sdk.json"
